### PR TITLE
CP-32840 drop legacy ssl support

### PR DESCRIPTION
**Pull request by lippirk**
Don't allow clients to modify the ciphers used

Signed-off-by: lippirk <ben.anson@citrix.com>

### CODE REVIEW

File: stunnel/stunnel_cache.ml [hunk 1]
```diff
@@ -146,31 +143,26 @@ let gc () = Mutex.execute m unlocked_gc
...
-        unlocked_gc ()
-      )
+  let now = Unix.gettimeofday () in
+  Mutex.execute m (fun () ->
+      let idx = !counter in
+      incr counter;
+      Hashtbl.add !times idx now;
+      Hashtbl.add !stunnels idx x;
+      let ep = { host = x.Stunnel.host; port = x.Stunnel.port; verified = x.Stunnel.verified } in
+      let existing =
```
Comment (lindig) [inline stunnel/stunnel_cache.ml]: Use `Hashtbl.find` (and deal with `Not_found`) or `Hashtbl.find_opt` and avoid a race between `mem` and `find`.

**Comment by edwintorok** [comment]
I think the target here might have to be a feature branch, or we'd have to merge the xapi change first, otherwise the build would fail.

File: stunnel/stunnel_cache.ml (hunk 1 above)
Comment (psafont) [reply stunnel/stunnel_cache.ml]: while I agree that it should be changed, I think it's a matter of style: this is executed while holding the mutex, otherwise we'd have races with the following `replace` as well.

**Comment by lindig** [comment]
```

**Comment by lindig** [comment]
```
Processing  1/2: [xapi-libs-transitional: dune runtest]
+ /home/opam/.opam/4.08/bin/dune "runtest" "-j" "71" (CWD=/home/opam/.opam/4.08/.opam-switch/build/xapi-libs-transitional.master)
- File "stunnel/stunnel.ml", line 17, characters 0-6:
- 17 | open D
-      ^^^^^^
- Error (warning 33): unused open D.
- File "stunnel/stunnel.ml", line 18, characters 4-8:
- 18 | let trim = String.trim
-          ^^^^
- Error (warning 32): unused value trim.
```

**Comment by lindig** [comment]
Is this up to date? There were conflicts and a failed Travis CI and now the target branch was updated.

**Comment by lippirk** [comment]
> Is this up to date? There were conflicts and a failed Travis CI and now the target branch was updated.

no - i need to resolve the conflicts with the changes from REQ-789 - it will be ready with my next push

**Comment by lindig** [comment]
```
# File "stunnel/stunnel.ml", line 155, characters 21-48:
# 155 |     ; "ciphers = " ^ Xcp_const.good_ciphersuites
#                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Xcp_const
```
Does this depend other PRs or are we missing dependencies in `dune` files?

**Comment by lippirk** [comment]
> ```
> # File "stunnel/stunnel.ml", line 155, characters 21-48:
> # 155 |     ; "ciphers = " ^ Xcp_const.good_ciphersuites
> #                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> # Error: Unbound module Xcp_const
> ```
> 
> Does this depend other PRs or are we missing dependencies in `dune` files?

i have everything pinned locally, so i believe it to be working correctly. i'm running builds to try and fix anything i have broken

**Comment by psafont** [comment]
Same problem with https://github.com/xapi-project/xen-api/pull/4029 I don't see a PR opened for xcp-idl, which the dune dependency is pointing to

**Comment by lindig** [comment]
Is Travis expected to work for the target branch?
